# IMPORT ALL THE LIBRARIES

In [2]:
# import all libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [3]:
# Set display options
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 100)

sns.set_style("darkgrid")
sns.set_palette("husl")

# LOAD AND EXPLORE DATA

In [4]:
df = pd.read_csv('ai_impact_jobs_2010_2025.csv')
df.head(6)

,job_id,posting_year,country,region,city,company_name,company_size,industry,job_title,seniority_level,ai_mentioned,ai_keywords,ai_intensity_score,core_skills,ai_skills,salary_usd,salary_change_vs_prev_year_percent,automation_risk_score,reskilling_required,ai_job_displacement_risk,job_description_embedding_cluster,industry_ai_adoption_stage
0,836b4774-702e-49ef-93d3-2f255ce1e910,2018,Brazil,South America,London,NextGen Technologies,Small,Education,Policy Analyst,Lead,True,reinforcement learning,0.81,"Research, Project Management, Business Analysis",reinforcement learning,61586,12.68,0.11,True,Low,14,Growing
1,43699e93-7b15-4728-a4c6-9e41ff438a25,2015,UAE,Middle East,Singapore,Future Solutions,Medium,Energy,Data Scientist,Executive,False,NaN,0.04,"Research, SQL, Business Analysis, Python, Clou...",NaN,62045,-3.98,0.71,False,High,19,Emerging
2,fc9d1854-3cbf-4bab-90df-77304dfc59df,2016,Nepal,South Asia,Sydney,Future Analytics,Startup,Finance,Product Manager,Junior,False,NaN,0.15,"Statistics, Project Management, Cloud Computin...",NaN,27035,3.55,0.86,False,High,2,Emerging
3,05c1c7d3-2add-4919-91eb-f6c78bfe23d1,2015,Spain,Europe,Nairobi,Global Technologies,Large,Government,Data Scientist,Mid,False,NaN,0.19,"Cloud Computing, SQL, Project Management, Comm...",NaN,72894,-2.80,0.70,False,Low,15,Emerging
4,5e739937-d1b0-44d7-935c-7ebb3fc1f6e8,2014,Taiwan,East Asia,Sydney,Future Technologies,Small,Manufacturing,ML Engineer,Lead,False,NaN,0.11,"SQL, Python, Communication, Software Engineeri...",NaN,57215,0.85,0.87,False,High,13,Emerging
5,3eaa8f95-6ada-4e08-ad17-ca924707d66f,2022,Colombia,South America,London,Future Analytics,Enterprise,Government,ML Engineer,Senior,True,deep learning,0.77,"Cloud Computing, Research, Data Analysis",deep learning,67379,8.47,0.29,True,High,3,Growing

In [5]:
print("rows * columns")
df.shape

rows * columns

(5000, 22)

In [6]:
# structure of dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 22 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   job_id                              5000 non-null   object
 1   posting_year                        5000 non-null   int64
 2   country                             5000 non-null   object
 3   region                              5000 non-null   object
 4   city                                5000 non-null   object
 5   company_name                        5000 non-null   object
 6   company_size                        5000 non-null   object
 7   industry                            5000 non-null   object
 8   job_title                           5000 non-null   object
 9   seniority_level                     5000 non-null   object
 10  ai_mentioned                        5000 non-null   bool
 11  ai_keywords                         1623 non-null   object
 12  ai_intensity_score                  5000 non-null   float64
 13  core_skills                         5000 non-null   object
 14  ai_skills                           1623 non-null   object
 15  salary_usd                          5000 non-null   int64
 16  salary_change_vs_prev_year_percent  5000 non-null   float64
 17  automation_risk_score               5000 non-null   float64
 18  reskilling_required                 5000 non-null   bool
 19  ai_job_displacement_risk            5000 non-null   object
 20  job_description_embedding_cluster   5000 non-null   int64
 21  industry_ai_adoption_stage          5000 non-null   object
dtypes: bool(2), float64(3), int64(3), object(14)
memory usage: 791.1+ KB

### DUPLICATE VALUES

In [7]:
# check duplicates in the dataset
df.duplicated().sum()

0

### MISSING VALUES

In [8]:
missing_data = df.isnull().sum()
missing_percent = (missing_data / len(df)) * 100
missing_summary = pd.DataFrame({
    'Missing Count': missing_data,
    'Missing %': missing_percent.round(2)
})
display(missing_summary[missing_summary['Missing Count'] > 0])

             Missing Count  Missing %
ai_keywords           3377      67.54
ai_skills             3377      67.54

In [9]:
print("The only columns which has missing values is : ")
df[["ai_keywords", "ai_skills"]].isna().sum()

The only columns which has missing values is :

ai_keywords    3377
ai_skills      3377
dtype: int64

### ALWAYS MAKE COPY OF YOUR DATASET BEFORE MOBIFYING

In [10]:
df_copy = df.copy()

### FILLING MISSING VALUES

In [11]:
# fill the missing values with 'Unknown'
df_copy[["ai_keywords", "ai_skills"]] = df_copy[["ai_keywords", "ai_skills"]].replace(np.NaN, 'Unknown')

In [12]:
df_copy[["ai_keywords", "ai_skills"]].isnull().sum()

ai_keywords    0
ai_skills      0
dtype: int64

### DATASET OVERVIEW

In [13]:
print("The unique values in each column is : ")
# print(f"Companies : {df['company_name'].nunique()}")
data_overview = pd.DataFrame(
    {'Company' : [df['company_name'].nunique()],
     'Country' : [df['country'].nunique()],
     'Region' : [df['region'].nunique()],
     'city' : [df['city'].nunique()],
     'industries' : [df['industry'].nunique()],
     'job_titles' : [df['job_title'].nunique()],
     'senior_level' : [df['seniority_level'].nunique()]
    }
)
changed = data_overview.T
changed.columns = ["Unique_vals"]
changed

The unique values in each column is :

              Unique_vals
Company                16
Country                44
Region                  9
city                   14
industries              9
job_titles             10
senior_level            6

### CHANGING DATA TYPES

# DATA PREPROCESSING AND FEATURE ENGINEERING